import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";

const InterFont = Inter({
  variable: "--font",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Scout",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${InterFont.variable} 
      `}
      >
        {children}
      </body>
    </html>
  );
}
